### ISSUE TITLE
[bug]夜间模式下注册页面UI错误

### ISSUE THREAD

**Issue by CharlotteFallices** [Mikubill/Biu#4]
![image](https://user-images.githubusercontent.com/47619464/76076112-274b2700-5fd9-11ea-9a5b-05b011e6bcb8.png)
------
==
The Issue is under Artistic License 2.0.
That's all.

**Comment by CharlotteFallices** [comment]
可以加一个Unstable分支嘛......(小声
有一点点想法==

**Comment by CharlotteFallices** [comment]
emmmmmm......
![image](https://user-images.githubusercontent.com/47619464/76083724-3043f480-5fe9-11ea-9235-120ac4efc0b6.png)

**Comment by Mikubill** [comment]
[...继续操作..]那个应该是服务器端回应，估计是短时间重复登录了（？

**Comment by Mikubill** [comment]
> 可以加一个Unstable分支嘛......(小声

是想做本repo的collaborator嘛（瞄

如果不是特别大改动（如更换API等）可以直接pr到master呀

**Comment by CharlotteFallices** [comment]
直到目前为止的所有功能都可以用Markdown内嵌HTML实现(笑)
而且Kingfisher也太麻烦了嘛,用到的那些curl就可以实现的说......
还有为什么不去买一本`Refactoring`学习一下呢==

**Comment by Mikubill** [comment]
...所以说咱很菜嘛QwQ
用Kingfisher的话主要是为了方便路由呀请求重试呀什么的

**Comment by CharlotteFallices** [comment]
QAQ
密码忘记了诶......

**Comment by Mikubill** [comment]
去 https://biu.moe/#/User/forgotPw 重置一下吧w

**Comment by CharlotteFallices** [comment]
==
